### ISSUE TITLE
[FEATURE] - Display openweathermap logo

### ISSUE THREAD

**Issue by alexstan67** [sky-unlimited/wef_2023#202]
**Issue Description**
Display the logo somewhere, it's mandatoryl when using the [One Call API 3.0](https://openweathermap.org/price)

Could be displayed bottom on the modal appearing in the pilot preferences.

**Desired Behaviour**
...

**Acceptance Criteria**
...

**Additional Considerations**
...

**Resources**
...

**Impact**
...

**Related Issues**
...

**Comment by christinasugiono** [comment]
<img width="694" alt="image" src="https://github.com/sky-unlimited/wef_2023/assets/74747669/bd053b42-a50d-4461-a763-6e8832721982">

Its here in the Airports#show
