### ISSUE TITLE
[IMPROVEMENT] `app/views/airports/show.html.erb` to accomodate rating and comments

### ISSUE THREAD

**Issue by christinasugiono** [sky-unlimited/wef_2023#225]
- [ ] display the avatar's of other pilots that have setup the viewed airport in their pilot's prefs. We priority on staff members, then pilots, then student (see below)
- [ ] Be possible to rate the airport (max 5 stars)
- [ ] Be possible to comment on an airport (only create and display only only the last one if existing)

**Comment by christinasugiono** [comment]
@alexstan67 I'm thinking of doing the schema like this, so `pilot` can only **rate** an `airport` once, but `pilot` can **comment** on `airport` multiple times (but we only display the latest comment). Let me know if you have any feedback :D

<img width="695" alt="image" src="https://github.com/sky-unlimited/wef_2023/assets/74747669/311762c7-257f-4cd3-9af4-9942de861634">

**Comment by alexstan67** [comment]
Meeting 17/05
- Create just a table comment including the rating: 1 evaluation = 1 rating + (0;;n) comments
- We keep only the last comment for a user / airport
- rating is mandatory, coment optional
- We sort by having a comment + created_at desc
- If possible don't reload the whole page on create (turbo)
