### ISSUE TITLE
[REFACTOR] - Drop `pilot_pref` table and `is_private_pilot` `is_ultralight_pilot` columns after making sure all data transfer works

### ISSUE THREAD

**Issue by christinasugiono** [sky-unlimited/wef_2023#229]
**Issue Description**

- [x] Drop `pilot_pref` table after making sure `preferences` table replace the need
- [x] Remove `is_private_pilot` `is_ultralight_pilot` columns from `preferences` table after making sure `certificates` table replace the need

**Desired Behaviour**
...

**Acceptance Criteria**
...

**Additional Considerations**
...

**Resources**
...

**Impact**
...

**Related Issues**
Needs #224

**Comment by alexstan67** [comment]
@christinasugiono : For this one, even if we deploy on `staging`, we'll still not deploy on `production`, so I guess this issue is to be affected on milestone 1.0? WDYT?

**Comment by christinasugiono** [comment]
I think as long as the data transfer in the production is already okay and everything is working smoothly, I can start cleaning these table and columns. :D
