### ISSUE TITLE
[IMPROVEMENT] - Hide pilot activities when user hasn't follow

### ISSUE THREAD

**Issue by christinasugiono** [sky-unlimited/wef_2023#257]
**Issue Description**

**Desired Behavior**
- [ ] When pilot is on his own profile, no airport he visited on activity log (already displayed on map)
- [ ] When pilot is on his own profile, we display all other activities
- [ ] When pilot is following other pilots, we display activity log of this other pilots (but we need to display the username)

**Acceptance Criteria**
...

**Additional Considerations**
...

**Resources**
...

**Impact**
...

**Related Issues**
...

**Comment by alexstan67** [comment]
As per #258, can be closed.
