### ISSUE TITLE
[IMPROVEMENT] - Secure Airports API

### ISSUE THREAD

**Issue by alexstan67** [sky-unlimited/wef_2023#275]
**Issue Description**
Our `app/controllers/api/v1/airports_controller.rb` is not secured as it currently can be called outside our server.

**Root cause:** `config/initializers/cors.rb` was not setup until yet!

**Desired Behavior**
Calls of our API should not be accessible outside the application server.

**Acceptance Criteria**
For instance, this should return nothing:
`````bash
curl https://weekend-fly.com/api/v1/airports/find\?query\=luxembourg
`````

**Additional Considerations**
...

**Resources**
https://www.youtube.com/watch?v=sh4WrNGDvQM

**Impact**
...

**Related Issues**
...

**Comment by christinasugiono** [comment]
> CORS is a security feature implemented by browsers to prevent web pages from making requests to a different domain than the one that served the web page

CORS only prevent request from other web browser (client-side request), so to prevent request from terminal or server-side, it is not sufficient. 

We need to implement something like an API key authentication (I will try this if you don't mind :D @alexstan67 )
